### ISSUE TITLE
Cmake rejects boost-serialization

### ISSUE THREAD

**Issue by tylerdq** [jclaar/zork#7]
When trying to build with cmake on my installation of KISS Linux I get the following error:

```
  29   | CMake Error at /usr/lib64/cmake/Boost-1.86.0/BoostConfig.cmake:141 (find_package):
  30   │   Found package configuration file:
  31   │
  32   │     /usr/lib64/cmake/boost_serialization-1.86.0/boost_serialization-config.cmake
  33   │
  34   │   but it set boost_serialization_FOUND to FALSE so package
  35   │   "boost_serialization" is considered to be NOT FOUND.  Reason given by
  36   │   package:
  37   │
  38   │   No suitable build variant has been found.
  39   │
  40   │   The following variants have been tried and rejected:
  41   │
  42   │   * libboost_serialization.so.1.86.0 (shared, Boost_USE_STATIC_LIBS=ON)
  43   │
  44   │ Call Stack (most recent call first):
  45   │   /usr/lib64/cmake/Boost-1.86.0/BoostConfig.cmake:262 (boost_find_component)
  46   │   /usr/share/cmake-3.30/Modules/FindBoost.cmake:610 (find_package)
  47   │   CMakeLists.txt:12 (find_package)
  48   │
  49   │
  50   │ -- Configuring incomplete, errors occurred!
````

These are the build commands I've tried:

```
cmake --build build
cmake --build install
```

```
cmake --build --preset x64-release
cmake --build install
```

Do you know if this is something related to the package itself or how boost is configured?

**Comment by jclaar4** [comment]
Hi Tyler,

This looks like a Boost configuration issue. The code uses the filesystem, system, and serialization libraries for saving and restoring games, so it looks like it's not finding at least serialization. (I checked on my system, and it looks like it just aborts whenever it doesn't find one library. It checks serialization first, so I'd guess you're probably also missing system and filesystem too.)

I'm more of a Windows guy so I'm not versed on all the different Linux distributions and their different installation systems, but at least on Ubuntu using apt, you should be able to install it all using
sudo apt install libboost-dev

Also, there are Linux-specific presets that you can install:
cmake --preset linux-release
cmake --preset linux-debug


These will create build folders in the out/build directory. You can then run
cmake --build out/build/linux-debug
or
cmake --build out/build/linux-release

The zork output will be in out/build/linux-debug/mdlfun or out/build/linux-release/mdlfun.

Hope that works for you! (I should probably update the readme to make this more clear. :-) )

**Comment by tylerdq** [comment]
Thank you. I'm having trouble getting a well-configured boost install so I'm giving up for now but I'm sure the information you shared is quite valuable to include in the readme.
